import 'package:flutter/material.dart';


List prodect = [
  {
    'Image':'asset/img/product image/img21.png',
    'name':'Galaxy Watch 6 Classic',
    'prize1':300.0,
    'prize':140.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star_half_outlined,
    'rating':3.6,
    'public':1523,
    'qty':1,
  },
  {
    'Image':'asset/img/product image/img1.png',
    'name':'the smart Oxford collar shirt',
    'prize1':500.0,
    'prize':300.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':4.0,
    'public':2372,
    'qty':1,
  },
  {
    'Image':'asset/img/product image/img3.png',
    'name':'Clinique Happy™ For Men Cologne Spray',
    'prize1':225.0,
    'prize':70.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':3.8,
    'public':6535,
    'qty':1,
  },
  {
    'Image':'asset/img/product image/img4.png',
    'name':'UA Unisex Project Rock 6 \'The Bull\'',
    'prize1':1200.0,
    'prize':980.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':4.0,
    'public':6563,
    'qty':1,
  },
];
List prodect2 = [
  {
    'Image':'asset/img/product image/img6.png',
    'name':'VILLAIN Mashup Classic',
    'prize1':900.0,
    'prize':700.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':4.3,
    'public':8645,
    'qty':1,
  },
  {
    'Image':'asset/img/product image/img5.png',
    'name':'Nike Dunk Low Retro SE',
    'prize1':600.0,
    'prize':480.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':4.2,
    'public':4520,
    'qty':1,
  },{
    'Image':'asset/img/product image/img7.png',
    'name':'YAZOLE Turntable Men Quartz Watch',
    'prize1':340.0,
    'prize':200.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':3.9,
    'public':7522,
    'qty':1,
  },
  {
    'Image':'asset/img/product image/img8.png',
    'name':'Double-Knit Joggers(Polo Ralph Lauren)',
    'prize1':1500.0,
    'prize':1200.0,
    'Icon3':Icons.star,
    'Icon4':Icons.star,
    'rating':4.3,
    'public':5420,
    'qty':1,
  },
];